import { Event } from "./types/events.type";

export const MOCK_EVENTS: Event[] = [
	{
		id: "1",
		title: "Build with AI - Event",
		mode: "physical",
		location: "Universiti Putra Malaysia, Serdang",
		dateStart: new Date("2025-05-24T08:00:00"),
		dateEnd: new Date("2025-05-24T16:30:00"),
		ticketType: "External Ticketing",
		maxParticipants: 100,
		image: "/images/events/figma.png",
		status: "upcoming",
		description: "Level up your developer skills by building smart applications with Gemini, Vertex AI, and NotebookLM.",
		tags: [
			{ tag: "GenAI", presetColor: "red" },
			{ tag: "Gemini", presetColor: "indigo" },
			{ tag: "Vertex AI", presetColor: "red" },
			{ tag: "NotebookLM", presetColor: "indigo" },
		],
		registrationLink: "#",
		isActive: true,
	},
	{
		id: "2",
		title: "Women In Tech",
		mode: "physical",
		location: "Universiti Putra Malaysia, Serdang",
		dateStart: new Date("2025-06-21T10:00:00"),
		dateEnd: new Date("2025-06-21T16:30:00"),
		ticketType: "External Ticketing",
		maxParticipants: 60,
		image: "/images/events/flutter.png",
		status: "upcoming",
		description: "An empowering panel discussion and technical workshop focused on resume builders and technology career paths.",
		tags: [
			{ tag: "Networking", presetColor: "red" },
			{ tag: "Workshops", presetColor: "red" },
			{ tag: "AI Resume Builder", presetColor: "indigo" },
		],
		registrationLink: "#",
		isActive: true,
	},
	{
		id: "3",
		title: "Annual Grand Meeting (AGM)",
		mode: "physical",
		location: "Universiti Putra Malaysia, Serdang",
		dateStart: new Date("2025-06-22T18:00:00"),
		dateEnd: new Date("2025-06-22T22:00:00"),
		ticketType: "By Invitation Only",
		maxParticipants: 50,
		image: "/images/events/mobileAI.png",
		status: "upcoming",
		description: "Reviewing UPM core developmental metrics, community achievements, and electing the new executive committee.",
		tags: [
			{ tag: "Reporting", presetColor: "red" },
			{ tag: "Awards", presetColor: "indigo" },
		],
		registrationLink: "#",
		isActive: true,
	},
	{
		id: "4",
		title: "Flutter Workshop",
		mode: "physical",
		location: "Universiti Putra Malaysia, Serdang",
		dateStart: new Date("2025-07-15T09:00:00"),
		dateEnd: new Date("2025-07-15T17:00:00"),
		ticketType: "External Ticketing",
		maxParticipants: 80,
		image: "/images/events/tailwindcss.png",
		status: "upcoming",
		description: "A comprehensive deep dive into Flutter widgets, cross-platform layouts, and visual dashboard styling.",
		tags: [
			{ tag: "Mobile", presetColor: "indigo" },
			{ tag: "Flutter", presetColor: "red" },
			{ tag: "Development", presetColor: "indigo" },
		],
		registrationLink: "#",
		isActive: true,
	},
	{
		id: "5",
		title: "UI/UX Design Bootcamp",
		mode: "physical",
		location: "Universiti Putra Malaysia, Serdang",
		dateStart: new Date("2025-08-02T10:00:00"),
		dateEnd: new Date("2025-08-02T18:00:00"),
		ticketType: "External Ticketing",
		maxParticipants: 40,
		image: "/images/events/uiux.png",
		status: "upcoming",
		description: "Learn advanced Figma auto-layouts, responsive wireframing, prototyping, and modern design system values.",
		tags: [
			{ tag: "Design", presetColor: "red" },
			{ tag: "UI", presetColor: "indigo" },
			{ tag: "UX", presetColor: "red" },
			{ tag: "Figma", presetColor: "indigo" },
		],
		registrationLink: "#",
		isActive: true,
	},
	{
		id: "6",
		title: "DevFest UPM 2024",
		mode: "physical",
		location: "FCSIT, Universiti Putra Malaysia",
		dateStart: new Date("2024-11-23T08:00:00"),
		dateEnd: new Date("2024-11-23T17:00:00"),
		ticketType: "Past Event",
		maxParticipants: 150,
		image: "/images/events/figma.png",
		status: "past",
		googleDriveLink: "https://drive.google.com/drive/folders/1a2b3c4d5e6f7g8h9i0j_devfest",
		description: "Our flagship developer festival! 150+ students gathered to explore Vertex AI, Firebase GenAI capabilities, and Google Cloud with Google Developer Experts.",
		tags: [
			{ tag: "DevFest", presetColor: "red" },
			{ tag: "GenAI", presetColor: "indigo" },
			{ tag: "Cloud", presetColor: "red" },
		],
		registrationLink: "#",
		isActive: true,
	},
	{
		id: "7",
		title: "Flutter Mobile Bootcamp",
		mode: "physical",
		location: "DK1, Universiti Putra Malaysia",
		dateStart: new Date("2024-10-12T09:00:00"),
		dateEnd: new Date("2024-10-13T17:00:00"),
		ticketType: "Past Event",
		maxParticipants: 80,
		image: "/images/events/flutter.png",
		status: "past",
		googleDriveLink: "https://drive.google.com/drive/folders/2b3c4d5e6f7g8h9i0j1k_flutter",
		description: "A comprehensive 2-day hands-on bootcamp. Over 80+ beginners successfully learned mobile state management, auto-layouts, and built their first cross-platform apps.",
		tags: [
			{ tag: "Flutter", presetColor: "indigo" },
			{ tag: "Mobile", presetColor: "red" },
			{ tag: "Bootcamp", presetColor: "indigo" },
		],
		registrationLink: "#",
		isActive: true,
	},
	{
		id: "8",
		title: "Study Jams: Google Cloud Essentials",
		mode: "physical",
		location: "Lab 3, Universiti Putra Malaysia",
		dateStart: new Date("2024-09-18T14:00:00"),
		dateEnd: new Date("2024-09-18T17:00:00"),
		ticketType: "Past Event",
		maxParticipants: 50,
		image: "/images/events/mobileAI.png",
		status: "past",
		googleDriveLink: "https://drive.google.com/drive/folders/3c4d5e6f7g8h9i0j1k2l_cloud",
		description: "An intensive guided session exploring Google Cloud Console, virtual machines, networking fundamentals, and hands-on laboratory badges on Cloud Skills Boost.",
		tags: [
			{ tag: "Cloud", presetColor: "red" },
			{ tag: "Study Jams", presetColor: "indigo" },
		],
		registrationLink: "#",
		isActive: true,
	},
	{
		id: "9",
		title: "UI/UX Design Masterclass",
		mode: "physical",
		location: "DK2, Universiti Putra Malaysia",
		dateStart: new Date("2024-05-11T10:00:00"),
		dateEnd: new Date("2024-05-11T16:00:00"),
		ticketType: "Past Event",
		maxParticipants: 60,
		image: "/images/events/uiux.png",
		status: "past",
		googleDriveLink: "https://drive.google.com/drive/folders/4d5e6f7g8h9i0j1k2l3m_uiux",
		description: "A highly visual masterclass detailing wireframing, prototyping, user-testing models, and advanced responsive auto-layouts inside Figma.",
		tags: [
			{ tag: "Design", presetColor: "red" },
			{ tag: "UI/UX", presetColor: "indigo" },
		],
		registrationLink: "#",
		isActive: true,
	},
	{
		id: "10",
		title: "Annual Grand Meeting 2024",
		mode: "physical",
		location: "DK5, Universiti Putra Malaysia",
		dateStart: new Date("2024-04-20T19:00:00"),
		dateEnd: new Date("2024-04-20T22:30:00"),
		ticketType: "Past Event",
		maxParticipants: 70,
		image: "/images/events/tailwindcss.png",
		status: "past",
		googleDriveLink: "https://drive.google.com/drive/folders/5e6f7g8h9i0j1k2l3m4n_agm",
		description: "Reviewing our operational milestones, key leadership achievements, financial summaries, and electing the new executive committee.",
		tags: [
			{ tag: "AGM", presetColor: "indigo" },
			{ tag: "Leadership", presetColor: "red" },
		],
		registrationLink: "#",
		isActive: true,
	},
];
